# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js project to Azure Function App - cwiki-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "." # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: "16.x" # set this to the node version to use (supports 8.x, 10.x, 12.x)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v4

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: "Resolve Project Dependencies Using Npm"
        shell: bash
        run: |
          pushd '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          npm install --legacy-peer-deps
          npm run build --if-present
          echo "$GITHUB_SHA" > sha.txt
          popd

      - name: "Run Azure Functions Action"
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: "cwiki-app"
          slot-name: "Production"
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_E3DC81AB858A4055B936D9E7DB965EE0 }}
          scm-do-build-during-deployment: true
          enable-oryx-build: false

      - name: "E2E Check HttpTrigger Result"
        shell: pwsh
        run: |
          $i = 0
          while ($i -lt 10) {
            sleep 10
            $RESPONSE = $(curl "${{ steps.fa.outputs.app-url }}/api/HttpTrigger")
            $RESULT = ($RESPONSE -eq "$env:GITHUB_SHA")
            if ($RESULT) {
              exit 0
            }
            $i = $i + 1
          }
          exit 1
